# Generated by Django 2.1.15 on 2020-07-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(db_column='AID')),
                ('mid', models.CharField(blank=True, db_column='MID', max_length=12, null=True)),
                ('cid', models.CharField(blank=True, db_column='CID', max_length=20, null=True)),
                ('tl', models.CharField(blank=True, db_column='TL', max_length=6, null=True)),
                ('fn', models.CharField(blank=True, db_column='FN', max_length=200, null=True)),
                ('ln', models.CharField(blank=True, db_column='LN', max_length=200, null=True)),
                ('dob', models.CharField(blank=True, db_column='DOB', max_length=10, null=True)),
                ('mp', models.CharField(blank=True, db_column='MP', max_length=16, null=True)),
                ('eid', models.CharField(blank=True, db_column='EID', max_length=200, null=True)),
                ('tg', models.CharField(blank=True, db_column='TG', max_length=24, null=True)),
                ('ms', models.CharField(blank=True, db_column='MS', max_length=12, null=True)),
                ('g', models.CharField(blank=True, db_column='G', max_length=1, null=True)),
                ('pc', models.CharField(blank=True, db_column='PC', null=True)),
                ('ed', models.CharField(blank=True, db_column='ED', max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
            ],
            options={
                'db_table': 'Fact_Members',
                'managed': False,
            },
        ),
    ]
